version: '3.8'

services:
  soksabay-frontend:
    image: bongchang/soksabay-frontend:latest
    container_name: soksabay-frontend
    restart: always
    networks:
      - proxy
      - default

  soksabay-backend:
    image: bongchang/booking-tour-app:latest
    container_name: soksabay-backend
    restart: always
    networks:
      - proxy
      - default
    environment:
      # Database Configuration
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      # App Settings
      SERVER_PORT: 8080
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      FRONTEND_URL: https://soksabay-frontend.wmad-demo.psewmad.org

      # Security & External Services
      SECRET_KEY: ${SECRET_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}

networks:
  proxy:
    external: true
  default:
    driver: bridge